### ISSUE TITLE
Adding support for *79+*2 haplotype

### ISSUE THREAD

**Issue by maarjl** [PacificBiosciences/pangu#16]
I am testing Pangu on a set of samples sequenced with PacBio Hifi reads (full genome). A subset of those samples are validated carriers of *79+*2 (or *13+*2) hybrid tandem. However, currently Pangu does not seem to support this configuration and instead calls three haplotypes per sample. I wonder if there is an easy way I could include this tandem to Pangu's list of possible outcomes? Thanks in advance!

**Comment by zeeev** [comment]
Hi @maarjl , 

Apologies for the late reply, and thank you for brining this to our attention. If you're working with WGS, please also check out pb-StarPhase which might provide you the diplotype calls you're looking for (linked below). As we don't have a timeline for this feature in Pangu, I'm going to close the ticket. 

https://github.com/PacificBiosciences/pb-StarPhase
